[package]
name = "binrw"
version = "1.4.0"
authors = ["jam1garner <jam1.mcleod@hotmail.com>"]
edition = "2018"
repository = "https://github.com/jam1garner/binrw"
license = "MIT"
description = "A Rust crate for helping read structs from binary data using ✨macro magic✨"
readme = "README.md"

[dependencies]
binrw_derive = { version = "1.3", path = "../binrw_derive" }
lazy_static = { version = "1.4" , optional=true }
rpds = "0.8.0"

[dev-dependencies]
modular-bitfield = "0.9"

[features]
default = ["std"]
std = []
debug_template = ["std", "lazy_static", "binrw_derive/debug_template"]
